### PR TITLE
Row background color + fix

### PR DESCRIPTION
**Pull request by AdamPalka**
-Added row background color. Now it's possible to use defined in document header colors as row
background color. Added example.
-Merging fork with original master branch (Consistent spacing).
-Fixed problem with appending int to Appendable.

### CODE REVIEW

**Comment by ullenboom** [comment]
Merged some lines to the master.
Didn't commit changes that brings to many null to the code. null is only "valid" if no var-arg is given. Pls also remove the possibility that style can be null.

**Comment by AdamPalka** [comment]
Sorry fot the nulls. Before I change my code, please look at my proposals:

1. Row background color.

I need some way to set row background color. To eliminate nulls I can
propose duplicating "row" method so we would get:

RtfRow row( final RtfPara... cells )
RtfRow row(final int rowBackgroundColor, final RtfPara... cells )

The first method won't use the second one but copying code will be
necessary. It's why I allowed null, so I won't need to copy almost the same
code. But You're right, I shouldn't do that.

2. null style

I just use RtfHeaderStyle.NORMAL as default style, also delete checking
null in other methods:

public static RtfTextPara p( final RtfText... texts )
  {
      return p( RtfHeaderStyle.NORMA, texts );
  }

Can you accept those changes?

2015-07-31 23:11 GMT+02:00 Christian Ullenboom <notifications@github.com>:

**Comment by ullenboom** [comment]
small portions of duplicate code is fine for me and we can refactor to a private method later anyway.

would it make sense to let the colors start at index 1? so we could use rowBackgroundColor 0 as some kind of "default".

PS: If the final is not neccessary you can remove it from the method parameter.

**Comment by AdamPalka** [comment]
I would rather allow user to define color 0 and just add to method row(RtfPara ...), row(RtfText...) and row(Object ...) description: "By default, color defined under index 0 is used as row background color.". I would add it to your readme file as well. As you know, if color index 0 isn't defined, RTF document will look good. But it's your decision, it's your tool :)

Also I found out that you're building jRtf with JRE 1.7 or newer and in POM file you have 1.6. We should stay with 1.6, more users will be able to use your library. Change your project settings in Eclipse or use Eclipse Mars. Mars shows errors like this one:
List<RtfPara> paras = new ArrayList<>();

**Comment by ullenboom** [comment]
adding row(RtfPara ...), row(RtfText...) and row(Object ...) to the API is
the best thing. we should not add something that is undefinied in RTF.

**Comment by AdamPalka** [comment]
So I suppose it's decided, user colors start at index 1. Will you change it?

**Comment by ullenboom** [comment]
maybe we do something else.

the rtf spec says:

Each definition must be delimited by a semicolon, even if the definition is
omitted. If a color definition is omitted, the RTF reader uses its default
color. The example below defines the default color table used by Word. The
first color is omitted, as shown by the semicolon following the \colortbl
control word. The missing definition indicates that color 0 is the ''auto''
color.

so we could start at 1 and use 0 as "auto" as described. then
RtfHeaderColor should be changed that a valid definition starts at 1.

one change would be in RtfHeaderColor, public RtfHeader at( int colorindex
), 0 should not be allowed.

and if we do the change there would be a change in the class RTF from

out.append( "\n{\\colortbl" );
to

      out.append( "\n{\\colortbl;" );

then when we add the rows, 0 as a color index is always valid.

whats your take on this?

**Comment by AdamPalka** [comment]
Of course we should use semicolon version. But to be clear, we'll get three methods:
`public static RtfRow row( Object... cells ){ return row( 0, cells ); }`
`public static RtfRow row( RtfText... cells ){ return row( 0, cells ); }`
`public static RtfRow row( RtfPara... cells ){ return row( 0, cells ); }`
And three more methods allowing row background selection, eg.
`public static RtfRow row( int backgroundColor, RtfPara... cells )`
In the last method we use "if" to check if the backgroud color have 0. Thanks to it we won't duplicate code.

**Comment by ullenboom** [comment]
agreed

**Pull request closed without merging**
