### PR TITLE
Provide windows-1252 escaped fallbacks for UTF-8 characters

### PR DESCRIPTION
**Pull request by oddbjornkvalsund**
Previously jrtf only provided a hardcoded `?` as fallback for UTF-8 characters. This PR provides a proper windows-1252 hex escaped fallback instead. See https://en.wikipedia.org/wiki/Rich_Text_Format#Character_encoding for reference.

### CODE REVIEW

**Comment by oddbjornkvalsund** [comment]
Note that I had to make some changes to be able to build the project on Java 12+33 and Maven 3.6.0.

**Comment by oddbjornkvalsund** [comment]
Also; would it be possible to have a release of version 0.8 to Maven Central any time soon?

**Comment by oddbjornkvalsund** [comment]
Any feedback here?

**Comment by ullenboom** [comment]
This library was explicitly made to work with older Java versions and
Android, GWT and Google App Engine in mind. Probable I will make a
different "edition" for new Java versions.

**Comment by oddbjornkvalsund** [comment]
Fair enough, supporting older Java versions is commendable. Would you like me to submit a PR with the changes to `build.xml` and `pom.xml` reverted?

**Pull request merged**
